global using DTCBillingSystem.Core.Models;
global using DTCBillingSystem.Core.Models.Entities;
global using DTCBillingSystem.Core.Models.Enums;
global using DTCBillingSystem.Core.Interfaces;
global using Microsoft.EntityFrameworkCore;
global using System.Linq.Expressions;
global using System.Collections.Generic;
global using System.Threading.Tasks;
global using System; 